architecture: DETR
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_vb_normal_pretrained.pdparams
hidden_dim: 256
use_focal_loss: True


DETR:
  backbone: ResNet
  transformer: AnchorDETRTransformer
  detr_head: AnchorDETRHead
  post_process: DETRBBoxPostProcess


ResNet:
  # index 0 stands for res2
  depth: 50
  norm_type: bn
  freeze_at: 0
  return_idx: [3] # in Anchor DETR R50DC, Only return the last feature map of ResNet50.
  # FIXME: Replace stride with dilation in the last convolutional layer of ResNet50.
  lr_mult_list: [0, 0.1, 0.1, 0.1]
  num_stages: 4
  freeze_norm: True # Freeze the norm of the backbone.
  dilation: True

AnchorDETRTransformer:
  num_queries: 100
  position_embed_type: sine
  nhead: 8
  num_encoder_layers: 6
  num_decoder_layers: 6
  dim_feedforward: 1024
  dropout: 0.1
  activation: relu
  num_query_position: 300
  num_query_pattern: 3


AnchorDETRHead:
  num_mlp_layers: 3
  num_classes: 80


DETRLoss:
  loss_coeff: {class: 2, bbox: 5, giou: 2, mask: 1, dice: 1}
  aux_loss: True


HungarianMatcher:
  matcher_coeff: {class: 2, bbox: 5, giou: 2}
